version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=pass@word1
    expose:
      - '1433'
  api:
    image: serviceapi
    environment: 
      - ConnectionStrings__DbConnString=Server=db; Database=Excuses; User=sa; Password=pass@word1;
    ports:
      - '80:80'
    links:
      - db
volumes:
  db:
    driver: local